apiVersion: v1
kind: ReplicationController
metadata:
  name: camunda-contr
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: camunda
    tier: frontend
spec:
  replicas: 1
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #  app: microservices
  #  tier: frontend
  # Pod Template
  template:
    metadata:
      labels:
        app: camunda
        tier: frontend
    spec:
      containers:
      - name: camunda
        image: camunda/camunda-bpm-platform:7.5.0
        resources:
          # The resources specification for each Pod, more details here:
          # http://kubernetes.io/v1.1/docs/design/resources.html#resource-specifications
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          # Environment variables that will be available in the Pod
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # delete these values. The Pod will fallback on a hardcoded IP address
        ports:
          # More details on the container ports here,
          # http://kubernetes.io/v1.1/docs/api-reference/v1/definitions.html#_v1_containerport
          # The port exposed by the container
        - containerPort: 8080
          hostPort: 8080
